# Generated by Django 5.0.1 on 2024-04-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_rename_qusetion_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
